### PR TITLE
Making underwater exploration drone (ROV)

### PR DESCRIPTION
**Pull request by laukejas**
Half a year ago, I  became interested in underwater exploration, and decided to build an ROV (Remotely Operated underwater Vehicle). While there are commercial options available, the ones that fit my ultimate goal - reaching the deepest lake in Lithuania, Tauragnas (62.5 m) seemed priced quite unreasonably. So instead, I decided to tackle this challenge on my own, researching the complicated engineering required to build such an ROV from scratch with a minimal budget. There were many challenges to overcome - pressure proofing, building compact electronics, engineering thrusters and lights that can work submerged, routing electrical connections through watertight bulkheads, not to mention the software part - communication with topside via a thin tether, providing video feed, forwarding controls, as well as building robust autonomous recovery procedures in case of lost signal. This is the story of how this idea developed into reality through many iterations, failed attempts, to the final design that will be featured live during this presentation.

### CODE REVIEW

**Comment by laukejas** [comment]
@kareiva Took me a while to find time to cut the footage, but here it is [https://youtu.be/G_WbJOpmkFs](url)

**Comment by kareiva** [comment]
Fantastic! Thank you so much.

**Comment by Pawka** [comment]
@laukejas Can you please upload slides here as well? Thanks!

**Comment by laukejas** [comment]
@Pawka Sure, here it is: https://ufile.io/b9c3xm5x

**Pull request merged**
